# Generated by Django 2.2.12 on 2021-11-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingWeb', '0003_auto_20211101_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'digital'), (1, 'carton'), (2, 'foods'), (3, 'cosmetics'), (4, 'clothes'), (5, 'pet_supplies'), (6, 'baby_product'), (7, 'other')], default=7, verbose_name='category'),
        ),
    ]
