# Generated by Django 2.2.12 on 2021-11-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingWeb', '0004_commodity_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_buying',
            old_name='total',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='group_buying',
            name='discount',
        ),
        migrations.AddField(
            model_name='commodity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=88, max_digits=12, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='group_buying',
            name='discounting_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='discounting_rate'),
        ),
        migrations.AddField(
            model_name='group_buying',
            name='identity_token',
            field=models.CharField(default='', max_length=20, verbose_name='address_detailed'),
        ),
        migrations.AddField(
            model_name='group_buying',
            name='initiator',
            field=models.CharField(default='', max_length=20, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='sharing_discounting',
            name='identity_token',
            field=models.CharField(default='', max_length=20, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='sharing_discounting',
            name='price',
            field=models.IntegerField(default=0, verbose_name='total_price'),
        ),
    ]
