# Generated by Django 2.2.12 on 2021-11-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingWeb', '0005_auto_20211112_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_buying',
            name='discounting_rate',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=15, verbose_name='discounting_rate'),
        ),
        migrations.AlterField(
            model_name='group_buying',
            name='initiator',
            field=models.CharField(default='', max_length=20, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='sharing_discounting',
            name='discounting_rate',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=15, verbose_name='discounting_rate'),
        ),
    ]
