# Generated by Django 2.2.12 on 2021-11-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingWeb', '0006_auto_20211116_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentator',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shoppingWeb.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default='1', verbose_name='amount'),
        ),
    ]
