# Generated by Django 2.2.12 on 2021-11-16 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingWeb', '0007_auto_20211116_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingWeb.User'),
        ),
    ]
