# Generated by Django 2.2.12 on 2021-11-17 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingWeb', '0008_auto_20211116_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='commodities',
        ),
        migrations.CreateModel(
            name='Order_Commodities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default='1', verbose_name='amount')),
                ('commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingWeb.Commodity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingWeb.Order')),
            ],
        ),
    ]
