# Generated by Django 2.2.12 on 2021-11-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingWeb', '0009_auto_20211117_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
    ]
