# Generated by Django 3.2.8 on 2021-11-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingWeb', '0011_auto_20211118_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentator',
        ),
    ]
