# Generated by Django 2.2.12 on 2021-10-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=20, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='price')),
            ],
        ),
    ]
