# Generated by Django 2.2.12 on 2021-10-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='info',
            field=models.CharField(default=None, max_length=100, verbose_name='info'),
        ),
    ]
