# Generated by Django 2.2.12 on 2021-10-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20211027_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub',
            field=models.CharField(default='', max_length=200, verbose_name='publisher'),
        ),
    ]
